"""Añadir Author y Post, y FK en Book

Revision ID: 398b93f294a4
Revises: f3e4bdaafa44
Create Date: 2025-11-17 01:58:37.590445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '398b93f294a4'
down_revision = 'f3e4bdaafa44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_table('users')
    #op.drop_table('genres')
    #op.drop_table('books_have_genres')
    #op.drop_table('cart_items')
    #op.drop_table('books')
    # ### end Alembic commands ###
    op.create_table('authors',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('bio', sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
    )
    
    op.create_table('posts',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(length=140), nullable=False),
        sa.Column('body', sa.Text(), nullable=False),
        sa.Column('timestamp', sa.DateTime(), nullable=True),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.add_column('books', sa.Column('author_name', sa.String(length=100), nullable=True))
    
    op.add_column('books', sa.Column('author_id', sa.Integer(), nullable=True))
    op.create_foreign_key(
        'fk_books_author_id', 'books', 'authors', ['author_id'], ['id']
    )
def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_books_author_id', 'books', type_='foreignkey')
    op.drop_column('books', 'author_id')
    op.drop_column('books', 'author_name')
    op.drop_table('posts')
    op.drop_table('authors')
    
    # ### end Alembic commands ###
